### ISSUE TITLE
Nice concepts but too much magic :-)

### ISSUE THREAD

**Issue by esdras** [ianrumford/drink_maker#1]
Hi, how are you doing?

Didn't find a way to comment on your blog, please tell me if there is another place where I can post this.

First of all, thank you for sharing this, your blog post presents concepts on metaprogramming and other not so obvious Elixir concepts, I think it's great that we know about these concepts. I'm also a ruby programmer and I like metaprogramming but these days I rarely use it, only in very specific cases and only if there is no alternative. 

I could be mistaken, mainly because your example is contrived for simplicity (as you stated in your post), but the problem you're facing could be solved with simple function calls, right? Why instead of all that machinery with module attributes and registering the drink menu you didn't just make a generic module called DrinkMaker with the functions you needed for both Coffee and Tea? Just reuse the function in both modules, like `DrinkMaker.make_dring(state, :boil_whater)` and that's it!

By reusing functions like I suggested above you still have the benefits of pattern matching and your code is much easier to maintain because everything is explicit. After I finished your post I came back to this part:

> I also thought about structuring the dsl into a hierarchical form such as a module for the different ways of boiling water, one for cleaning the cups, and so on.
> 
> But everthing I thought of introduced constraints, confusion and complexity into what was currently quite a simple, easy to understand and elegant solution.

I honestly think that the solution above is better, well, granted you wouldn't have the chance to mess with elixir meta programming and all that cool concepts, but for a real app it would be a better choice, in my opinion :-)

I rarely comment on posts like this, I understand that programming is also about taste and I apologise if i'm being intrusive. I'm aware that maybe I didn't understand your post well enough to see the value of your approach.

Thank you and please keep sharing your journey through the Elixir land 😄

**Comment by ianrumford** [comment]
Hi,

No better place to comment. And thanks for taking the time and effort to do
so; I appreciate it.

You points are valid ones but, IMHO, don't address scale, participation or
override.  I'll try to explain.

BTW yes the DrinkMaker is simple; the real application was a general
purpose mechanism to build Elixir asts.  I already had a "CoffeMaker" for
asts and was working on a "TeaMaker" in another application.

I could have just one DrinkMaker module with all the variants in it but it
would not scale to, say, 100s (1000s!) of different drinks (asts).  In my
real application my modules were already > 1000 lines long. That too big to
mange I feel.  And it was only becoming worse.   How would / could I add
the functions for a BeerMaker, CocktailMaker, etc, etc to DrinkMaker - the
module would just keep on growing to a potentially unlimited size.

If there is only one (very big) DrinkMaker, participation / sharing is not
a problem.  But as soon as you decide you have to have another module,
sharing functions becomes very hard and tightly coupled because you always
have to remember where the e.g. boil_water variant is defined.

Overriding e.g. boil_water is also a really hard problem.  Unlike Ruby, in
Elixir you can't redefine a function at runtime.  So if you need to
override, you have to create another module with the different boil_water
variant and remember to use that module when you want hot water.

I also wanted to separate (abstract) the dsl "verbs" (e.g.
make_my_favourite_drink) away from the underlying functions:  I didn't want
the implementation of the verb to be coupled tightly to the underlying
functions. Having a /drink_menu/ provides a simple dictionary to map dsl
verbs to functions.

Although I've written a lot of Ruby, I'd say that Clojure is my other
principal language.  Clojure was the first functional language I learnt and
it really did teach me to think about how to so stuff in a different way.
Many of the ideas I'm using in Elixir, are derived from my experience in
Clojure. That's not to say I've got it right of course :-)

Thanks again.

**Comment by esdras** [comment]
Got it!

You presented a way to achieve polymorphism in Elixir when dealing with a _huge_ scale (lots of variations). I'm not a clojure programmer but I'm a fan of Rich Hikey and at first glance your post seemed to contradict his view on simplicity, hence my comment.

The takeaway here seems to be: Know when to use that approach. Would you say that for simple cases when you have less variations, simply using functions or protocols is the way to go?

As always, it is good to know these different approaches and that Elixir's metaprogramming capabilities are very powerful allowing these kind of solutions.

Thank you.

**Comment by ianrumford** [comment]
Glad it helped.

Yep "simple" is context sensitive.  This was the simplest way I could see
given what I wanted to achieve.

But for much less scale / variation, your approach would be the correct one
i.e simple functions.

Re protocols, I don't think they would help solve my problems.

As it happens, my solution is _loosely_ based on how Clojure multimethods
work (or at least how I understand them).

:-)
